### ISSUE TITLE
Game Crashes When in Load Profile Menu

### ISSUE THREAD

**Issue by WesternGamer** [sepluginloader/PluginLoader#27]
So I found this out from my Medieval Engineers version of PluginLoader so I tested in the SE version and the same thing happens.

The crash occurs when you click delete or rename when nothing is selected in the list on the load profile menu.

**Comment by austinvaness** [comment]
Is the issue just the delete button or does rename also crash?

**Comment by WesternGamer** [comment]
I did not test it as I had to go to sleep but I assume rename also crashes the game.

**Comment by austinvaness** [comment]
Fixed in version 1.9.0
