### ISSUE TITLE
Error while downloading whitelist hash: System.Net.WebException

### ISSUE THREAD

**Issue by Gusko-SVK** [sepluginloader/PluginLoader#30]
Greetings,
plugin list won't load. Any ideas?

Running as admin, SE starts and runs normally, plugin list is empty with a request to send logs.
Confirmed presence of PluginLoader files in the folder, loaded a world with it, to make sure.
.NET 4.7.2 downgrade didn't help, running 4.8 .
Tried disabling firewalls for a moment, even added my PC to DMZ (got static public IP, so I can't keep it on).
Killed AV & AS software too.
I suspect a dependency issue, possibly related to Win.7 SP1 that I'm running on.
KB4490628 and KB4474419 are installed tho.

If there is another dependency that I should handle, please let me know.

Core of the issue seems to be:
[PluginLoader] Downloading https://raw.githubusercontent.com/sepluginloader/PluginHub/main/plugins.sha1
[PluginLoader] Error while downloading whitelist hash: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at avaness.PluginLoader.Network.GitHub.DownloadFile(String name, String commit, String path)
   at avaness.PluginLoader.PluginList.TryDownloadWhitelistHash(String& hash)
   
[PluginLoader] REST API request failed: GET https://pluginstats.ferenczi.eu/Stats [The request was aborted: Could not create SSL/TLS secure channel.]

NOTE: Reaching
https://raw.githubusercontent.com/sepluginloader/PluginHub/main/plugins.sha1
or
https://pluginstats.ferenczi.eu/Stats
by other means, does give me what seems to be a valid response.

Please see the attached log file for details.
[SpaceEngineers_20220217_112655749.log](https://github.com/sepluginloader/PluginLoader/files/8088222/SpaceEngineers_20220217_112655749.log)

Thx.

**Comment by austinvaness** [comment]
Does this fix the issue? I suspect the problem is that Windows 7 doesn't support tls 1.2 by default. You can install it manually via the instructions on the GitHub page.
[Release.zip](https://github.com/sepluginloader/PluginLoader/files/8089386/Release.zip)

**Comment by viktor-ferenczi** [comment]
Found this: [How do I enable TSL 1.2 on Windows 7](https://manage.accuwebhosting.com/knowledgebase/3008/how-do-i-enable-tls-1-2-on-windows-7.html)

**Comment by Gusko-SVK** [comment]
Hi,
thx for prompt reply.

Tried manual install as suggested, got following error:
Exception occurred: System.IO.FileLoadException: Could not load file or assembly 'file:///B:\PARA\steamapps\common\SpaceEngineers\Bin64\PluginLoader.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///B:\PARA\steamapps\common\SpaceEngineers\Bin64\PluginLoader.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

Died on SE start.

**Comment by Gusko-SVK** [comment]
Hi, thx again for help,
had both files selected while looking to unblock them, so the unblock option didn't show up in properties.
My mistake.
It seems to be working now.

Thx again for help.
Best regards,
Gusko

**Comment by austinvaness** [comment]
This fix was published today. You should be able to switch back to the workshop version.
