### ISSUE TITLE
Current instructions for launch options constantly crashes SE for me

### ISSUE THREAD

**Issue by AgeofExile** [sepluginloader/PluginLoader#42]
I navigated to the most recent release, downloaded the most recent release, followed directions to add the given files to Bin64 of Space Engineers, and I put this string in the game launcher window: -plugin PluginLoader.dll.  

I think my problems are the launch option currently.

Every time I try to open the game it crashes
I like the released plugins and using plugin loader - any help would be appreciated

**Comment by viktor-ferenczi** [comment]
Hi, If you can join the [Plugin Loader Discord](https://discord.gg/6ETGRU3CzR) and post your full game and loader logs, then we can help you right away. If not, then please attach your log files here.

Latest `SpaceEngineers_*.log` file by date from the `%AppData%\SpaceEngineers` directory.

Loader log should be in `C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64\Plugins`, unless you moved the game files to somewhere else.

**Comment by viktor-ferenczi** [comment]
Resolved by using the `Unblock` button on the DLLs
