### ISSUE TITLE
Plugin List can't be downloaded

### ISSUE THREAD

**Issue by Omega596** [sepluginloader/PluginLoader#44]
When I try to enter the plugin loader menu, it errors with this:
"An error occured while downloading the plugin list.
Please send your game log to the developers of Plugin Loader."
So, I did what the error told me to do:
"2023-05-06 18:45:43.092 - Thread:  26 ->  CreateDeviceInternal Steam Overlay OK
2023-05-06 18:45:43.092 - Thread:  26 ->  CreateDeviceInternal create swapchain
2023-05-06 18:45:45.750 - Thread:   1 ->  [PluginLoader] Starting - v1.11.0
2023-05-06 18:45:46.301 - Thread:   1 ->  [PluginLoader] Downloading https://raw.githubusercontent.com/sepluginloader/PluginHub/main/plugins.sha1
2023-05-06 18:45:47.081 - Thread:   1 ->  [PluginLoader] Downloading https://github.com/sepluginloader/PluginHub/archive/main.zip
2023-05-06 18:45:48.522 - Thread:   1 ->  [PluginLoader] Error while downloading whitelist: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at avaness.PluginLoader.Network.GitHub.GetStream(Uri uri)
   at avaness.PluginLoader.Network.GitHub.DownloadRepo(String name, String commit)
   at avaness.PluginLoader.PluginList.TryDownloadWhitelistFile(String file, String hash, PluginConfig config, PluginData[]& list)
2023-05-06 18:45:48.524 - Thread:   1 ->  [PluginLoader] No whitelist cache exists
2023-05-06 18:45:48.524 - Thread:   1 ->  [PluginLoader] WARNING: No plugins in the plugin list. Plugin list will contain local plugins only.
2023-05-06 18:45:48.700 - Thread:   1 ->  [PluginLoader] Found 0 plugins
2023-05-06 18:45:48.725 - Thread:   1 ->  [PluginLoader] Enabled plugins: None
2023-05-06 18:45:48.727 - Thread:  14 ->  [PluginLoader] Downloading plugin statistics anonymously...
2023-05-06 18:45:48.739 - Thread:   1 ->  [PluginLoader] Patching
..."
I seem to have everything on my side correctly set up.
Also the link where the main.zip is downloaded is erroring out with this:
"net::ERR_CERT_COMMON_NAME_INVALID"
and this monstrosity:
"Subject: dns.google

Issuer: GTS CA 1C3

Expires on: somewhere in the past.

Current date: now.

PEM encoded chain: 
-----BEGIN CERTIFICATE-----MIIF4zCCBMugAwIBAgIQVxsg7QvF2SkQD2Ch8qxD5jANBgkqhkiG9w0BAQsFADBGMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzETMBEGA1UEAxMKR1RTIENBIDFDMzAeFw0yMzA0MTcwODI2MjJaFw0yMzA3MTAwODI2MjFaMBUxEzARBgNVBAMTCmRucy5nb29nbGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDdeMMbM/VfP8555wFctX2K7Amox34rlYvwa5N6QO/6XD1rSluuxPnKl8ncnOs5UarLABRXURVyiVHEhClAW7Zn/wbiYPWuzxhCQOGW5wnz0ma1emmoSC9LPlzvQwOZ5w1sP63yUBIZcVQUAPsVYFBiiTH5mcfciMSWisI6prL+RhsRmUprWj5s1NZCbFsPRXk5MvK+HOpD+cZ7sur6FtazoXfaYcvyQqxzVa9SFQZgG0RLpZO4VV/6rMFF+Eqd+TGhR002JtuQJpfr0Cp3OTAL2vxEFShgVgNqcwTtsDgMitSopbAHaQpUKIhGDGY9lEkW2Ppm27yyR32TMZDCOEd9AgMBAAGjggL8MIIC+DAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUofIVNoGsOb9ojz+Nd6iFC5C8sbwwHwYDVR0jBBgwFoAUinR/r4XN7pXNPZzQ4kYU83E1HScwagYIKwYBBQUHAQEEXjBcMCcGCCsGAQUFBzABhhtodHRwOi8vb2NzcC5wa2kuZ29vZy9ndHMxYzMwMQYIKwYBBQUHMAKGJWh0dHA6Ly9wa2kuZ29vZy9yZXBvL2NlcnRzL2d0czFjMy5kZXIwgawGA1UdEQSBpDCBoYIKZG5zLmdvb2dsZYIOZG5zLmdvb2dsZS5jb22CECouZG5zLmdvb2dsZS5jb22CCzg4ODguZ29vZ2xlghBkbnM2NC5kbnMuZ29vZ2xlhwQICAgIhwQICAQEhxAgAUhgSGAAAAAAAAAAAIiIhxAgAUhgSGAAAAAAAAAAAIhEhxAgAUhgSGAAAAAAAAAAAGRkhxAgAUhgSGAAAAAAAAAAAABkMCEGA1UdIAQaMBgwCAYGZ4EMAQIBMAwGCisGAQQB1nkCBQMwPAYDVR0fBDUwMzAxoC+gLYYraHR0cDovL2NybHMucGtpLmdvb2cvZ3RzMWMzL2ZWSnhiVi1LdG1rLmNybDCCAQUGCisGAQQB1nkCBAIEgfYEgfMA8QB2AK33vvp8/xDIi509nB4+GGq0Zyldz7EMJMqFhjTr3IKKAAABh46JbWQAAAQDAEcwRQIgRsOroJ8O1tnuSrAgoloTbwS3yhMQY8qGjgn42EIzt5gCIQC27wFzvpDdoRcdDpAcP3xkvUxXvGf6cxM1H3/0juUPVAB3ALNzdwfhhFD4Y4bWBancEQlKeS2xZwwLh9zwAw55NqWaAAABh46JbT4AAAQDAEgwRgIhANgKz5h0lgok79NxqeRW5x37ilx3vIpQlg1hGo5EotL9AiEAhgtvjpe1XYn9Crmx6a5fX5q5flgrAl7JkoZ0ml58bkEwDQYJKoZIhvcNAQELBQADggEBAMtyHA7McLdFaaWLMMc5Th1PXoLfF4YQ8WKgwk1sm7omq8AyVVB3aaD5LpAoiUEQyMj3kVmZRCVit+rWmfhqHRWwthGMgQdpok3jgYtuMBYdJjmIkjMukQIYwk+YBJd9L1wytHE7AQJt0FIYzC6NtpkaOy+cGGi6dlSxEufF0K9fOfel2S5QMCIBh6EdWTXFYNWuIiH3D032a2zeHKB8oz9HQSAem30bqAhmgmRtZkAV50pE4bvwn58DPoeQKtvhabB0jLsXOfM/tOpEcj4PZ26G+wWHM6jOu28HgYj29fVoiMxKnPaM944kqwF2ftiHFb7AMMEJLtKaMKKeDScMGPE=-----END CERTIFICATE----------BEGIN CERTIFICATE-----MIIFljCCA36gAwIBAgINAgO8U1lrNMcY9QFQZjANBgkqhkiG9w0BAQsFADBHMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzEUMBIGA1UEAxMLR1RTIFJvb3QgUjEwHhcNMjAwODEzMDAwMDQyWhcNMjcwOTMwMDAwMDQyWjBGMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzETMBEGA1UEAxMKR1RTIENBIDFDMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPWI3+dijB43+DdCkH9sh9D7ZYIl/ejLa6T/belaI+KZ9hzpkgOZE3wJCor6QtZeViSqejOEH9Hpabu5dOxXTGZok3c3VVP+ORBNtzS7XyV3NzsXlOo85Z3VvMO0Q+sup0fvsEQRY9i0QYXdQTBIkxu/t/bgRQIh4JZCF8/ZK2VWNAcmBA2o/X3KLu/qSHw3TT8An4Pf73WELnlXXPxXbhqW//yMmqaZviXZf5YsBvcRKgKAgOtjGDxQSYflispfGStZloEAoPtR28p3CwvJlk/vcEnHXG0g/Zm0tOLKLnf9LdwLtmsTDIwZKxeWmLnwi/agJ7u2441Rj72ux5uxiZ0CAwEAAaOCAYAwggF8MA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUinR/r4XN7pXNPZzQ4kYU83E1HScwHwYDVR0jBBgwFoAU5K8rJnEaK0gnhS9SZizv8IkTcT4waAYIKwYBBQUHAQEEXDBaMCYGCCsGAQUFBzABhhpodHRwOi8vb2NzcC5wa2kuZ29vZy9ndHNyMTAwBggrBgEFBQcwAoYkaHR0cDovL3BraS5nb29nL3JlcG8vY2VydHMvZ3RzcjEuZGVyMDQGA1UdHwQtMCswKaAnoCWGI2h0dHA6Ly9jcmwucGtpLmdvb2cvZ3RzcjEvZ3RzcjEuY3JsMFcGA1UdIARQME4wOAYKKwYBBAHWeQIFAzAqMCgGCCsGAQUFBwIBFhxodHRwczovL3BraS5nb29nL3JlcG9zaXRvcnkvMAgGBmeBDAECATAIBgZngQwBAgIwDQYJKoZIhvcNAQELBQADggIBAIl9rCBcDDy+mqhXlRu0rvqrpXJxtDaV/d9AEQNMwkYUuxQkq/BQcSLbrcRuf8/xam/IgxvYzolfh2yHuKkMo5uhYpSTld9brmYZCwKWnvy15xBpPnrLRklfRuFBsdeYTWU0AIAaP0+fbH9JAIFTQaSSIYKCGvGjRFsqUBITTcFTNvNCCK9U+o53UxtkOCcXCb1YyRt8OS1b887U7ZfbFAO/CVMkH8IMBHmYJvJh8VNS/UKMG2YrPxWhu//2m+OBmgEGcYk1KCTd4b3rGS3hSMs9WYNRtHTGnXzGsYZbr8w0xNPM1IERlQCh9BIiAfq0g3GvjLeMcySsN1PCAJA/Ef5c7TaUEDu9Ka7ixzpiO2xj2YC/WXGsYye5TBeg2vZzFb8q3o/zpWwygTMD0IZRcZk0upONXbVRWPeyk+gB9lm+cZv9TSjOz23HFtz30dZGm6fKa+l3D/2gthsjgx0QGtkJAITgRNOidSOzNIb2ILCkXhAd4FJGAJ2xDx8hcFH1mt0G/FX0Kw4zd8NLQsLxdxP8c4CU6x+7Nz/OAipmsHMdMqUybDKwjuDEI/9bfU1lcKwrmz3O2+BtjjKAvpafkmO8l7tdufThcV4q5O8DIrGKZTqPwJNl1IXNDw9bg1kWRxYtnCQ6yICmJhSFm/Y3m6xv+cXDBlHz4n/FsRC6UfTd-----END CERTIFICATE----------BEGIN CERTIFICATE-----MIIFVzCCAz+gAwIBAgINAgPlk28xsBNJiGuiFzANBgkqhkiG9w0BAQwFADBHMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzEUMBIGA1UEAxMLR1RTIFJvb3QgUjEwHhcNMTYwNjIyMDAwMDAwWhcNMzYwNjIyMDAwMDAwWjBHMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzEUMBIGA1UEAxMLR1RTIFJvb3QgUjEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC2EQKLHuOhd5s73L+UPreVp0A8of2C+X0yBoJx9vaMf/vo27xqLpeXo4xL+Sv2sfnOhB2x+cWX3u+58qPpvBKJXqeqUqv4IyfLpLGcY9vXmX7wCl7raKb0xlpHDU0QM+NOsROjyBhsS+z8CZDfnWQpJSMHobTSPS5g4M/SCYe7zUjwTcLCeoiKu7rPWRnWr4+wB7CeMfGCwcDfLqZtbBkOtdh+JhpFAz2weaSUKK0PfyblqAj+lug8aJRT7oM6iCsVlgmy4HqMLnXWnOunVmSPlk9orj2XwoSPwLxAwAtcvfaHszVsrBhQf4TgTM2S0yDpM7xSma8ytSmzJSq0SPly4cpk9+aCEI3oncKKiPo4Zor8Y/kB+Xj9e1x3+naH+uzfsQ55lVe0vSbv1gHR6xYKu44LtcXFilWr06zqkUspzBmkMiVOKvFlRNACzqrOSbTqn3yDsEB750Orp2yjj32JgfpMpf/VjsPOS+C12LOORc92wO1AK/1TD7Cn1TsNsYqiA94xrcx36m97PtbfkSIS5r762DL8EGMUUXLeXdYWk70paDPvOmbsB4om3xPXV2V4J95eSRQAogB/mqghtqmxlbCluQ0WEdrHbEg8QOB+DVrNVjzRlwW5y0vtOUucxD/SVRNuJLDWcfr0wbrM7Rv1/oFB2ACYPTrIrnqYNxgFlQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU5K8rJnEaK0gnhS9SZizv8IkTcT4wDQYJKoZIhvcNAQEMBQADggIBAJ+qQibbC5u+/x6Wki4+omVKapi6Ist9wTrYggoGxval3sBOh2Z5ofmmWJyq+bXmYOfg6LEeQkEzCzc9zolwFcq1JKjPa7XSQCGYzyI0zzvFIoTgxQ6KfF2I5DUkzps+GlQebtuyh6f88/qBVRRiClmpIgUxPoLW7ttXNLwzldMXG+gnoot7TiYaelpkttGsN/H9oPM47HLwEXWdyzRSjeZ2axfG34arJ45JK3VmgRAhpuo+9K4l/3wV3s6MJT/KYnAK9y8JZgfIPxz88NtFMN9iiMG1D53Dn0reWVlHxYciNuaCp+0KueIHoI17eko8cdLiA6EfMgfdG+RCzgwARWGAtQsgWSl4vflVy2PFPEz0tv/bal8xa5meLMFrUKTX5hgUvYU/Z6tGn6D/Qqc6f1zLXbBwHSs09dR2CQzreExZBfMzQsNhFRAbd03OIozUhfJFfbdT6u9AWpQKXCBfTkBdYiJ23//OYb2MI3jSNwLgjt7RETeJ9r/tSQdirpLsQBqvFAnZ0E6yove+7u7Y/9waLd64NnHi/Hm3lCXRSHNboTXns5lndcEZOitHTtNCjv0xyBZm2tIMPNuzjsmhDYAPexZ3FL//2wmUspO8IFgV6dtxQ/PeEMMA3KgqlbbC1j+Qa3bbbP6MvPJwNQzcmRk13NfIRmPVNnGuV/u3gm3c-----END CERTIFICATE-----

Certificate Transparency:

SCT Google 'Xenon2023' log (Embedded in certificate, Verified)

SCT DigiCert Nessie2023 Log (Embedded in certificate, Verified)"

**Comment by austinvaness** [comment]
Something must be wrong with GitHub itself if you are getting certificate errors

**Comment by Omega596** [comment]
it still occurs

**Comment by Omega596** [comment]
maybe use git temporary to retrive data?

**Comment by austinvaness** [comment]
Is it still saying ERR_CERT_COMMON_NAME_INVALID when you open https://github.com/sepluginloader/PluginHub/archive/main.zip in a browser?

**Comment by Omega596** [comment]
Yep

пн, 22 мая 2023 г., 02:41 avaness ***@***.***>:

**Comment by austinvaness** [comment]
Then this problem is with your PC and I cant do anything. Try using a different browser like Firefox
