### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by Minecrafter8001** [sepluginloader/PluginLoader#45]
when I use plugin loader the game crashes
I've verified game files, launched without plugin loader, reset plugin list and reinstalled the loader and nothing works
heres the log:
[loader.log](https://github.com/sepluginloader/PluginLoader/files/11455284/loader.log)

**Comment by C-InfDef** [comment]
So the game launched normally without plugin loader?

**Comment by Minecrafter8001** [comment]
yes

**Comment by Minecrafter8001** [comment]
> So the game launched normally without plugin loader?

correction no it doesn't

**Comment by C-InfDef** [comment]
> > So the game launched normally without plugin loader?
> 
> correction no it doesn't

Hmm... when you verified your files, did it say it was requiring 1 file after?

**Comment by Minecrafter8001** [comment]
> > > So the game launched normally without plugin loader?
> > 
> > 
> > correction no it doesn't
> 
> Hmm... when you verified your files, did it say it was requiring 1 file after?

no. 
i just tested it and it works without any plugin loader files (pluginloader.dll, harmony0.dll and the plugins folder)

**Comment by C-InfDef** [comment]
Ok so it is functional now then?

**Comment by Minecrafter8001** [comment]
but it crashes with them there even if the launch options are removed

**Comment by Minecrafter8001** [comment]
> Ok so it is functional now then?

yes without plugin loader

**Comment by C-InfDef** [comment]
does it give any notification or is it a straight on crash? Probably try to ee if there are graphics card updates and windows updates needed. Your issue might just so happen to extend past the issues of the plugin loader.

**Comment by C-InfDef** [comment]
Not much I can help with sadly, I'm just another person with issues regarding this. :/

**Comment by Minecrafter8001** [comment]
just a crash with the automated bug report popup

**Comment by C-InfDef** [comment]
> just a crash with the automated bug report popup

yeah not much i can do :(

**Comment by Minecrafter8001** [comment]
all good was just making this to let the devs know

**Comment by Walshie1980** [comment]
Having the same issues, played fine for hours. Stopped for dinner and when I came back space engineers had updated and the games crashes when using the plugin launcher, but loads fine when using the normal SE launcher.

**Comment by khamseen** [comment]
Austin posted in the Discord to say he should have a fix out for the launcher within the hour.

**Comment by austinvaness** [comment]
Fixed in version 1.11.1
