### ISSUE TITLE
Server Side?

### ISSUE THREAD

**Issue by SpeedKore75** [sepluginloader/PluginLoader#48]
Hi, sorry, it's not really a question, but i have you wonderful tools for my hosted game (Huge thanks for that).
But we want to migrate on a Nitrado server. How can i lunch Pluginloader on my server?

Thanks :)

**Comment by austinvaness** [comment]
That's not possible. Plugin Loader exists to distribute modifications for the game client, not the server. Some client plugins may have server side torch plugins but you have to look at each plugin individually for that.
