### ISSUE TITLE
Duplicated Plugins button

### ISSUE THREAD

**Issue by kaedys** [sepluginloader/PluginLoader#52]
After the update today, the "plugins" button is visually duplicated over the Exit button (both at the main menu, and in-game).  Clicking it still exits, rather than opening the plugin menu, fortunately, but it's rather confusing to see.  Log file and config don't appear to have anything relevant, but attached just in case.

<img width="269" alt="20230720-184430-419622" src="https://github.com/sepluginloader/PluginLoader/assets/9020449/abf69953-d9ab-401e-987f-d164391d75f4">

[loader.log](https://github.com/sepluginloader/PluginLoader/files/12114616/loader.log)
[config.txt (renamed from .xml because Github refuses to upload XML files)](https://github.com/sepluginloader/PluginLoader/files/12114617/config.txt)

**Comment by austinvaness** [comment]
It was "No News Plugin"
https://github.com/sepluginloader/PluginHub/pull/242

**Comment by kaedys** [comment]
Ahhh, I definitely should have thought to check that, given that the news was also showing up.  Apologies >.<
