### ISSUE TITLE
Add instructions to Readme for manual install

### ISSUE THREAD

**Issue by Dave247** [sepluginloader/PluginLoader#53]
The readme should include some simple instructions on how to manually install the loader for those who are brand new to this and aren't able or don't want to use the associated [launcher ](https://github.com/sepluginloader/SpaceEngineersLauncher)for whatever reason. Basically just where the DLL files should go and what the expected folder structure should be.

**Comment by austinvaness** [comment]
The manual install method is no longer supported because Keen plans to remove the launch argument that makes it possible. If you have an issue with the launcher let me know, but soon there will be no alternative.

**Comment by Dave247** [comment]
Ah jeez, well that's a bit of a shame but it is what it is. I'm all good, I thought I had an issue but it turns out I was just an idiot and didn't read the instructions of the launcher fully, as I was trying to run it from my desktop and wondering why it wasn't doing anything.
