### ISSUE TITLE
Launcher says game version not supported!

### ISSUE THREAD

**Issue by Babesz12** [sepluginloader/PluginLoader#66]
So i watched both tutorials (telling the same thing) made sure my game version is okay (1.204 at this time),but when i start the launcher it says "Game verison not supported! Reguires 1.202.0 or later".
What did i do wrong here?

**Comment by austinvaness** [comment]
Please verify the install folder by going into Steam, right clicking the game in the list, and click Manage>Browse local files. The only way you can get this message is if the game is not up to date.

**Comment by Babesz12** [comment]
I did verify the install that didn't work, then i transferred the game to my m.2 drive, put the launcher in bin64 and now it works xD.
WTH?
